# Generated by Django 5.2.4 on 2025-07-30 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='科目名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三'), ('初一', '初一'), ('初二', '初二'), ('初三', '初三')], max_length=10, verbose_name='年级')),
                ('class_name', models.CharField(max_length=20, verbose_name='班级名称')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='班主任')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'unique_together': {('grade_level', 'class_name')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考试名称')),
                ('exam_date', models.DateField(verbose_name='考试日期')),
                ('academic_year', models.CharField(max_length=20, verbose_name='学年')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'unique_together': {('name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('未知', '未知')], max_length=5, verbose_name='性别')),
                ('date_of_birth', models.DateField(verbose_name='出生日期')),
                ('status', models.CharField(choices=[('在讀', '在读'), ('轉學', '转学'), ('休學', '休学'), ('復學', '复学'), ('畢業', '毕业')], default='在讀', max_length=10, verbose_name='在校状态')),
                ('id_card_number', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号码')),
                ('student_enrollment_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='学籍号')),
                ('home_address', models.TextField(blank=True, null=True, verbose_name='家庭地址')),
                ('guardian_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='监护人姓名')),
                ('guardian_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='监护人联系电话')),
                ('entry_date', models.DateField(verbose_name='入学日期')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='毕业日期')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.class', verbose_name='当前班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='得分')),
                ('grade_rank_in_subject', models.IntegerField(blank=True, null=True, verbose_name='学科年级排名')),
                ('total_score_rank_in_grade', models.IntegerField(blank=True, null=True, verbose_name='总分年级排名')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='学生')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='科目')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'unique_together': {('student', 'exam', 'subject')},
            },
        ),
    ]
