# Generated by Django 5.2.4 on 2025-10-13 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三'), ('初一', '初一'), ('初二', '初二'), ('初三', '初三')], max_length=10, verbose_name='年级')),
                ('class_name', models.CharField(choices=[('1班', '1班'), ('2班', '2班'), ('3班', '3班'), ('4班', '4班'), ('5班', '5班'), ('6班', '6班'), ('7班', '7班'), ('8班', '8班'), ('9班', '9班'), ('10班', '10班'), ('11班', '11班'), ('12班', '12班'), ('13班', '13班'), ('14班', '14班'), ('15班', '15班'), ('16班', '16班'), ('17班', '17班'), ('18班', '18班'), ('19班', '19班'), ('20班', '20班')], max_length=20, verbose_name='班级名称')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考試名稱')),
                ('academic_year', models.CharField(blank=True, choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030')], help_text='請選擇考試所屬的學年 (例如: 2025-2026)', max_length=10, null=True, verbose_name='學年')),
                ('date', models.DateField(verbose_name='考試日期')),
                ('grade_level', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三'), ('初一', '初一'), ('初二', '初二'), ('初三', '初三')], max_length=10, verbose_name='適用年級')),
                ('description', models.TextField(blank=True, help_text='可选：填写考试的相关说明或注意事项', null=True, verbose_name='考试描述')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试管理',
                'ordering': ['-date', 'grade_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(choices=[('语文', '语文'), ('数学', '数学'), ('英语', '英语'), ('政治', '政治'), ('历史', '历史'), ('物理', '物理'), ('化学', '化学'), ('生物', '生物'), ('地理', '地理'), ('体育', '体育')], max_length=50, verbose_name='科目代码')),
                ('subject_name', models.CharField(help_text='通常与科目代码相同，但可以自定义', max_length=100, verbose_name='科目名称')),
                ('max_score', models.IntegerField(help_text='该科目在此次考试中的满分', verbose_name='满分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考试科目',
                'verbose_name_plural': '考试科目配置',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('语文', '语文'), ('数学', '数学'), ('英语', '英语'), ('政治', '政治'), ('历史', '历史'), ('物理', '物理'), ('化学', '化学'), ('生物', '生物'), ('地理', '地理'), ('体育', '体育')], max_length=50, verbose_name='科目')),
                ('score_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='分數')),
                ('grade_rank_in_subject', models.IntegerField(blank=True, null=True, verbose_name='学科年级排名')),
                ('class_rank_in_subject', models.IntegerField(blank=True, null=True, verbose_name='学科班级排名')),
                ('total_score_rank_in_grade', models.IntegerField(blank=True, null=True, verbose_name='总分年级排名')),
                ('total_score_rank_in_class', models.IntegerField(blank=True, null=True, verbose_name='总分班级排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '成績',
                'verbose_name_plural': '成績記錄',
                'ordering': ['exam__date', 'student__name', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=5, null=True, verbose_name='性别')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('grade_level', models.CharField(blank=True, choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三'), ('初一', '初一'), ('初二', '初二'), ('初三', '初三')], max_length=10, null=True, verbose_name='年級')),
                ('status', models.CharField(choices=[('在读', '在读'), ('转学', '转学'), ('休学', '休学'), ('复学', '复学'), ('毕业', '毕业')], default='在读', max_length=10, verbose_name='在校状态')),
                ('id_card_number', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='身份证号码格式不正确', regex='^[1-9]\\d{5}(18|19|20)\\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx]$')], verbose_name='身份证号码')),
                ('student_enrollment_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='学籍号')),
                ('home_address', models.TextField(blank=True, null=True, verbose_name='家庭地址')),
                ('guardian_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='监护人姓名')),
                ('guardian_contact_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='请输入正确的手机号码格式', regex='^1[3-9]\\d{9}$')], verbose_name='监护人联系电话')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入学日期')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='毕业日期')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['grade_level', 'current_class__class_name', 'name'],
            },
        ),
    ]
