# Generated by Django 5.2.5 on 2025-09-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='class_rank_in_subject',
            field=models.IntegerField(blank=True, null=True, verbose_name='学科班级排名'),
        ),
        migrations.AddField(
            model_name='score',
            name='total_score_rank_in_class',
            field=models.IntegerField(blank=True, null=True, verbose_name='总分班级排名'),
        ),
    ]
