# Generated by Django 5.2.5 on 2025-10-11 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students_grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='班主任'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('academic_year', 'name', 'grade_level')},
        ),
        migrations.AddField(
            model_name='examsubject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='students_grades.exam', verbose_name='考试'),
        ),
        migrations.AddField(
            model_name='score',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_grades.exam', verbose_name='考試'),
        ),
        migrations.AddField(
            model_name='score',
            name='exam_subject',
            field=models.ForeignKey(blank=True, help_text='关联到具体的考试科目配置', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_grades.examsubject', verbose_name='考试科目'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_grades.class', verbose_name='当前班级'),
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='students_grades.student', verbose_name='學生'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade_level', 'class_name')},
        ),
        migrations.AlterUniqueTogether(
            name='examsubject',
            unique_together={('exam', 'subject_code')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'exam', 'subject')},
        ),
    ]
