# Generated by Django 5.2.5 on 2025-09-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_grades', '0002_score_class_rank_in_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='入学日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=5, null=True, verbose_name='性别'),
        ),
    ]
