# Generated by Django 5.2.4 on 2025-09-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_grades', '0003_alter_student_date_of_birth_alter_student_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030')], help_text='請選擇考試所屬的學年 (例如: 2025-2026)', max_length=10, null=True, verbose_name='學年'),
        ),
    ]
