# Generated by Django 5.2.5 on 2026-04-01 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_grades', '0004_alter_class_cohort_alter_exam_grade_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如"数学培优班名单"', max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('simple', '简单筛选'), ('advanced', '高级筛选')], default='advanced', max_length=20, verbose_name='规则类型')),
                ('rule_config', models.JSONField(help_text='筛选条件 JSON 配置', verbose_name='规则配置')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filter_rules', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '保存的筛选规则',
                'verbose_name_plural': '保存的筛选规则',
                'db_table': 'saved_filter_rules',
                'ordering': ['-last_used_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilterResultSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_config_snapshot', models.JSONField(verbose_name='规则配置快照')),
                ('result_snapshot', models.JSONField(verbose_name='筛选结果快照')),
                ('snapshot_name', models.CharField(help_text='如"期中考试-数学培优班"', max_length=100, verbose_name='快照名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_snapshots', to='students_grades.exam', verbose_name='关联考试')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='students_grades.savedfilterrule', verbose_name='使用的规则')),
            ],
            options={
                'verbose_name': '筛选结果快照',
                'verbose_name_plural': '筛选结果快照',
                'db_table': 'filter_result_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='savedfilterrule',
            index=models.Index(fields=['user', '-last_used_at'], name='saved_filte_user_id_c008f2_idx'),
        ),
        migrations.AddIndex(
            model_name='savedfilterrule',
            index=models.Index(fields=['rule_type'], name='saved_filte_rule_ty_8ec232_idx'),
        ),
        migrations.AddIndex(
            model_name='filterresultsnapshot',
            index=models.Index(fields=['user', '-created_at'], name='filter_resu_user_id_a11476_idx'),
        ),
        migrations.AddIndex(
            model_name='filterresultsnapshot',
            index=models.Index(fields=['exam', '-created_at'], name='filter_resu_exam_id_80b091_idx'),
        ),
        migrations.AddIndex(
            model_name='filterresultsnapshot',
            index=models.Index(fields=['rule', '-created_at'], name='filter_resu_rule_id_d58a4e_idx'),
        ),
    ]
