# Generated by Django 5.2.5 on 2026-04-15 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_grades', '0005_add_filter_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('start', models.DateTimeField(verbose_name='开始时间')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='全天事件')),
                ('event_type', models.CharField(choices=[('exam', '考试'), ('meeting', '会议'), ('activity', '活动'), ('reminder', '提醒'), ('other', '其他')], default='other', max_length=20, verbose_name='类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('grade', models.CharField(blank=True, default='', max_length=50, verbose_name='年级')),
                ('visibility', models.CharField(choices=[('personal', '个人'), ('grade', '年级'), ('school', '全校')], default='personal', max_length=20, verbose_name='可见性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '日程',
                'verbose_name_plural': '日程',
                'db_table': 'calendar_events',
                'ordering': ['start'],
            },
        ),
    ]
