# Generated by Django 5.2.5 on 2026-04-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_grades', '0007_allow_calendar_event_creator_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='地点'),
        ),
    ]
