# Generated by Django 5.2.4 on 2025-07-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考試名稱')),
                ('date', models.DateField(verbose_name='考試日期')),
                ('grade_level', models.CharField(choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三'), ('初一', '初一'), ('初二', '初二'), ('初三', '初三')], max_length=10, verbose_name='適用年級')),
                ('description', models.TextField(blank=True, help_text='可選：填寫考試的具體說明或注意事項', null=True, verbose_name='考試描述')),
            ],
            options={
                'verbose_name': '考試',
                'verbose_name_plural': '考試管理',
                'ordering': ['-date', 'grade_level', 'name'],
            },
        ),
    ]
