# Generated by Django 5.2.4 on 2025-07-31 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_options_exam_academic_year_and_more'),
        ('students', '0003_alter_student_guardian_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('语文', '语文'), ('数学', '数学'), ('英语', '英语'), ('政治', '政治'), ('历史', '历史'), ('物理', '物理'), ('化学', '化学'), ('生物', '生物'), ('地理', '地理'), ('体育', '体育'), ('美术', '美术'), ('音乐', '音乐'), ('心理', '心理'), ('信息技术', '信息技术')], max_length=50, verbose_name='科目')),
                ('score_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='分數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='考試')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='students.student', verbose_name='學生')),
            ],
            options={
                'verbose_name': '成績',
                'verbose_name_plural': '成績記錄',
                'ordering': ['exam__date', 'student__name', 'subject'],
                'unique_together': {('student', 'exam', 'subject')},
            },
        ),
    ]
