# Generated by Django x.x.x on 2024-xx-xx xx:xx

from django.db import migrations

def remove_unwanted_subjects(apps, schema_editor):
    """
    删除不需要的科目数据
    """
    Score = apps.get_model('exams', 'Score')
    
    # 要删除的科目列表
    unwanted_subjects = ['美术', '音乐', '心理', '信息技术']
    
    # 删除这些科目的所有成绩记录
    deleted_count = 0
    for subject in unwanted_subjects:
        count = Score.objects.filter(subject=subject).count()
        if count > 0:
            print(f"删除科目 '{subject}' 的 {count} 条记录")
            Score.objects.filter(subject=subject).delete()
            deleted_count += count
    
    print(f"总共删除了 {deleted_count} 条记录")

def reverse_remove_unwanted_subjects(apps, schema_editor):
    """
    反向操作（通常为空，因为删除的数据无法恢复）
    """
    print("警告：无法恢复已删除的数据")
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_score'),  # 替换为您的最新迁移文件名
    ]

    operations = [
        migrations.RunPython(
            remove_unwanted_subjects,
            reverse_remove_unwanted_subjects,
        ),
    ]