# Generated by Django 4.2.23 on 2025-08-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_auto_20250731_2345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="subject",
            field=models.CharField(
                choices=[
                    ("语文", "语文"),
                    ("数学", "数学"),
                    ("英语", "英语"),
                    ("政治", "政治"),
                    ("历史", "历史"),
                    ("物理", "物理"),
                    ("化学", "化学"),
                    ("生物", "生物"),
                    ("地理", "地理"),
                    ("体育", "体育"),
                ],
                max_length=50,
                verbose_name="科目",
            ),
        ),
    ]
