# Generated by Django 5.2.4 on 2025-08-01 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_alter_score_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="score_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="分數"
            ),
        ),
        migrations.CreateModel(
            name="ExamSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_code",
                    models.CharField(
                        choices=[
                            ("语文", "语文"),
                            ("数学", "数学"),
                            ("英语", "英语"),
                            ("政治", "政治"),
                            ("历史", "历史"),
                            ("物理", "物理"),
                            ("化学", "化学"),
                            ("生物", "生物"),
                            ("地理", "地理"),
                            ("体育", "体育"),
                        ],
                        max_length=50,
                        verbose_name="科目代码",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(
                        help_text="通常与科目代码相同，但可以自定义",
                        max_length=100,
                        verbose_name="科目名称",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="该科目在此次考试中的满分（支持小数，如99.5）",
                        max_digits=6,
                        verbose_name="满分",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="科目在列表中的显示顺序", verbose_name="显示顺序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_subjects",
                        to="exams.exam",
                        verbose_name="考试",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试科目",
                "verbose_name_plural": "考试科目配置",
                "ordering": ["order", "subject_code"],
                "unique_together": {("exam", "subject_code")},
            },
        ),
        migrations.AddField(
            model_name="score",
            name="exam_subject",
            field=models.ForeignKey(
                blank=True,
                help_text="关联到具体的考试科目配置",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exams.examsubject",
                verbose_name="考试科目",
            ),
        ),
    ]
