# Generated by Django 5.2.4 on 2025-08-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_alter_score_score_value_examsubject_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exam", unique_together={("academic_year", "name", "grade_level")},
        ),
    ]
