# Generated by Django 5.2.4 on 2025-08-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_alter_exam_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examsubject",
            options={
                "ordering": ["subject_code"],
                "verbose_name": "考试科目",
                "verbose_name_plural": "考试科目配置",
            },
        ),
        migrations.RemoveField(model_name="examsubject", name="order",),
    ]
