# Generated by Django 5.2.4 on 2025-08-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_alter_examsubject_options_remove_examsubject_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examsubject",
            options={"verbose_name": "考试科目", "verbose_name_plural": "考试科目配置"},
        ),
        migrations.AlterField(
            model_name="examsubject",
            name="max_score",
            field=models.IntegerField(help_text="该科目在此次考试中的满分", verbose_name="满分"),
        ),
    ]
