# Generated by Django 5.2.4 on 2025-08-02 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0009_alter_examsubject_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="exam_subject",
            field=models.ForeignKey(
                blank=True,
                help_text="关联到具体的考试科目配置",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exams.examsubject",
                verbose_name="考试科目",
            ),
        ),
    ]
