# Generated by Django 5.2.4 on 2025-08-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0010_alter_score_exam_subject"),
        ("students", "0005_auto_20250731_1454"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["student", "exam"], name="score_student_exam_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["exam", "subject"], name="score_exam_subject_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["student", "subject"], name="score_student_subject_idx"
            ),
        ),
    ]
