# Generated by Django 5.2.4 on 2025-08-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_score_score_student_exam_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='grade_rank_in_subject',
            field=models.IntegerField(blank=True, null=True, verbose_name='学科年级排名'),
        ),
        migrations.AddField(
            model_name='score',
            name='total_score_rank_in_grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='总分年级排名'),
        ),
    ]
