# Generated by Django 5.2.4 on 2026-03-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='managed_grade',
            field=models.CharField(blank=True, choices=[('grade_7', '初一'), ('grade_8', '初二'), ('grade_9', '初三'), ('grade_10', '高一'), ('grade_11', '高二'), ('grade_12', '高三')], max_length=16, null=True, verbose_name='负责年级'),
        ),
    ]
