# Generated by Django 5.2.4 on 2026-03-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managed_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_cohort_year',
            field=models.IntegerField(blank=True, choices=[(2024, '2024级'), (2025, '2025级'), (2026, '2026级'), (2027, '2027级'), (2028, '2028级'), (2029, '2029级')], null=True, verbose_name='负责入学年份'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_section',
            field=models.CharField(blank=True, choices=[('junior', '初中'), ('senior', '高中')], max_length=8, null=True, verbose_name='负责学段'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='managed_grade',
            field=models.CharField(blank=True, choices=[('grade_7', '初一'), ('grade_8', '初二'), ('grade_9', '初三'), ('grade_10', '高一'), ('grade_11', '高二'), ('grade_12', '高三')], max_length=16, null=True, verbose_name='负责年级(旧)'),
        ),
    ]
