# Generated by Django 5.2.5 on 2026-04-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_managed_section_cohort_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='managed_cohort_year',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='managed_section',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='managed_grade',
            field=models.CharField(blank=True, choices=[('初一', '初一'), ('初二', '初二'), ('初三', '初三'), ('高一', '高一'), ('高二', '高二'), ('高三', '高三')], max_length=16, null=True, verbose_name='负责年级'),
        ),
    ]
