# Generated by Django 5.2.4 on 2026-04-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_managed_section_cohort_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='姓名'),
        ),
    ]
