# Generated by Django 5.2.4 on 2026-04-25 08:30

from django.db import migrations


def migrate_name(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    # 现有用户的 name = last_name + first_name（如"张"+"老师"="张老师"）
    for user in CustomUser.objects.filter(name=''):
        user.name = (user.last_name or '') + (user.first_name or '')
        user.save(update_fields=['name'])


def reverse_name(apps, schema_editor):
    # 回滚时把 name 清空（last_name/first_name 字段还在，不会丢数据）
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_name_field'),
    ]

    operations = [
        migrations.RunPython(migrate_name, reverse_name),
    ]
