# Generated by Django 5.2.4 on 2025-07-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(choices=[('1班', '1班'), ('2班', '2班'), ('3班', '3班'), ('4班', '4班'), ('5班', '5班'), ('6班', '6班'), ('7班', '7班'), ('8班', '8班'), ('9班', '9班'), ('10班', '10班'), ('11班', '11班'), ('12班', '12班'), ('13班', '13班'), ('14班', '14班'), ('15班', '15班'), ('16班', '16班'), ('17班', '17班'), ('18班', '18班'), ('19班', '19班'), ('20班', '20班')], max_length=20, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=5, verbose_name='性别'),
        ),
    ]
