# Generated by Django 5.2.4 on 2025-07-30 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_class_class_name_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='请输入正确的手机号码格式', regex='^1[3-9]\\d{9}$')], verbose_name='监护人联系电话'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='身份证号码格式不正确', regex='^[1-9]\\d{5}(18|19|20)\\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx]$')], verbose_name='身份证号码'),
        ),
    ]
