# Generated by Django 5.2.4 on 2025-07-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_guardian_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade_level', 'current_class__class_name', 'name'], 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('高一', '高一'), ('高二', '高二'), ('高三', '高三'), ('初一', '初一'), ('初二', '初二'), ('初三', '初三')], max_length=10, null=True, verbose_name='年級'),
        ),
    ]
