# Generated by Django 5.2.4 on 2025-08-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20250731_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('在读', '在读'), ('转学', '转学'), ('休学', '休学'), ('复学', '复学'), ('毕业', '毕业')], default='在读', max_length=10, verbose_name='在校状态'),
        ),
    ]
